services:
  ros2-jazzy:
    image: aliengo-ros2-jazzy
    build:
      context: ..
      dockerfile: docker/ros2-jazzy/Dockerfile

    volumes:
      - ..:/workspace/aliengo_competition
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
      - /etc/vulkan/icd.d:/etc/vulkan/icd.d:ro
      - /usr/share/glvnd/egl_vendor.d:/usr/share/glvnd/egl_vendor.d:ro
      - /etc/glvnd/egl_vendor.d:/etc/glvnd/egl_vendor.d:ro

    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all,compute,utility,graphics
      - NVIDIA_VISIBLE_DEVICES=all
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - QT_X11_NO_MITSHM=1
      - LIBGL_DRI3_DISABLE=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

    stdin_open: true
    tty: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    command: tail -f /dev/null
