#!/usr/bin/env python3
"""
Train a YOLOv8 object detector on the dataset collected by collect_dataset.py.

Prerequisites:
    pip install ultralytics

Usage:
    # Basic (after collect_dataset.py --yolo finishes):
    python scripts/train_yolo.py --data datasets/yolo_objects/data.yaml

    # With custom parameters:
    python scripts/train_yolo.py \
        --data datasets/yolo_objects/data.yaml \
        --model yolov8n.pt \
        --epochs 120 \
        --imgsz 640 \
        --batch 16 \
        --val_split 0.2 \
        --seed 42 \
        --project runs/yolo_detector

    # Resume interrupted training:
    python scripts/train_yolo.py \
        --data datasets/yolo_objects/data.yaml \
        --resume runs/yolo_detector/train/weights/last.pt
"""
from __future__ import annotations

import argparse
import random
import shutil
from pathlib import Path


def split_train_val(data_dir: Path, val_ratio: float, seed: int) -> None:
    """Move a fraction of images+labels from train/ to val/ for evaluation.

    Skips splitting if a non-empty val/ already exists.
    """
    img_train = data_dir / "images" / "train"
    lbl_train = data_dir / "labels" / "train"
    img_val = data_dir / "images" / "val"
    lbl_val = data_dir / "labels" / "val"

    # Don't re-split if val already has images
    if img_val.exists() and any(img_val.iterdir()):
        print(f"Val split already exists ({len(list(img_val.glob('*.png')))} images) — skipping split.")
        return

    img_val.mkdir(parents=True, exist_ok=True)
    lbl_val.mkdir(parents=True, exist_ok=True)

    images = sorted(img_train.glob("*.png"))
    if not images:
        images = sorted(img_train.glob("*.jpg"))
    if not images:
        raise FileNotFoundError(f"No images found in {img_train}")

    rng = random.Random(seed)
    rng.shuffle(images)

    n_val = max(1, int(len(images) * val_ratio))
    val_images = images[:n_val]

    moved = 0
    for img_path in val_images:
        stem = img_path.stem
        lbl_path = lbl_train / f"{stem}.txt"

        shutil.move(str(img_path), str(img_val / img_path.name))
        if lbl_path.exists():
            shutil.move(str(lbl_path), str(lbl_val / lbl_path.name))
        moved += 1

    print(f"Split: {len(images) - moved} train / {moved} val")


def patch_data_yaml(data_yaml: Path) -> None:
    """Ensure data.yaml points val to images/val (not images/train)."""
    text = data_yaml.read_text()
    if "val: images/train" in text:
        text = text.replace("val: images/train", "val: images/val")
        data_yaml.write_text(text)
        print(f"Updated {data_yaml}: val → images/val")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train YOLOv8 detector on simulator-collected dataset."
    )
    parser.add_argument(
        "--data", type=Path, required=True,
        help="Path to data.yaml (generated by collect_dataset.py --yolo).",
    )
    parser.add_argument(
        "--model", type=str, default="yolov8n.pt",
        help="Pretrained YOLO checkpoint to fine-tune (default: yolov8n.pt).",
    )
    parser.add_argument("--epochs", type=int, default=100, help="Training epochs.")
    parser.add_argument("--imgsz", type=int, default=640, help="Input image size.")
    parser.add_argument("--batch", type=int, default=16, help="Batch size (-1 for auto).")
    parser.add_argument("--val_split", type=float, default=0.2, help="Fraction of data for validation.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed.")
    parser.add_argument(
        "--project", type=str, default="runs/yolo_detector",
        help="Output directory for training results.",
    )
    parser.add_argument(
        "--resume", type=str, default=None,
        help="Path to last.pt to resume interrupted training.",
    )
    parser.add_argument(
        "--device", type=str, default=None,
        help="Device: 'cuda', 'cpu', or GPU id like '0' (default: auto).",
    )
    parser.add_argument(
        "--no_split", action="store_true",
        help="Skip automatic train/val splitting.",
    )
    args = parser.parse_args()

    # ── Validate inputs ─────────────────────────────────────────────
    data_yaml = args.data.resolve()
    if not data_yaml.exists():
        raise FileNotFoundError(f"data.yaml not found: {data_yaml}")

    data_dir = data_yaml.parent

    # ── Train/val split ──────────────────────────────────────────────
    if not args.no_split and args.resume is None:
        split_train_val(data_dir, val_ratio=args.val_split, seed=args.seed)
        patch_data_yaml(data_yaml)

    # ── Import ultralytics (heavy import, do it after arg parsing) ──
    try:
        from ultralytics import YOLO
    except ImportError:
        print("ultralytics not installed. Run:  pip install ultralytics")
        raise

    # ── Train ────────────────────────────────────────────────────────
    if args.resume:
        print(f"Resuming from {args.resume}")
        model = YOLO(args.resume)
        model.train(resume=True)
    else:
        model = YOLO(args.model)
        model.train(
            data=str(data_yaml),
            epochs=args.epochs,
            imgsz=args.imgsz,
            batch=args.batch,
            seed=args.seed,
            project=args.project,
            device=args.device,
            # Augmentation tuned for sim → sim transfer
            hsv_h=0.015,
            hsv_s=0.5,
            hsv_v=0.3,
            degrees=10.0,
            translate=0.1,
            scale=0.3,
            flipud=0.0,       # objects have gravity — no vertical flip
            fliplr=0.5,
            mosaic=1.0,
            mixup=0.1,
            patience=20,      # early stopping patience
            save=True,
            save_period=10,
            plots=True,
            verbose=True,
        )

    # ── Evaluate ─────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("Validation metrics:")
    print("=" * 60)
    metrics = model.val()
    print(f"  mAP50:    {metrics.box.map50:.4f}")
    print(f"  mAP50-95: {metrics.box.map:.4f}")

    # ── Export to ONNX ───────────────────────────────────────────────
    print("\nExporting to ONNX...")
    onnx_path = model.export(format="onnx", imgsz=args.imgsz)
    print(f"  ONNX model: {onnx_path}")

    # ── Summary ──────────────────────────────────────────────────────
    best_pt = Path(model.trainer.best) if hasattr(model, "trainer") else None
    print("\n" + "=" * 60)
    print("Training complete!")
    if best_pt and best_pt.exists():
        print(f"  Best weights: {best_pt}")
    print(f"  ONNX export:  {onnx_path}")
    print(f"\nTo use in your controller:")
    print(f"  from ultralytics import YOLO")
    print(f"  model = YOLO('{best_pt}')")
    print(f"  results = model(image, conf=0.5)")


if __name__ == "__main__":
    main()
